#!/bin/bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
asset_dir="$root/Sources/TokeniBar/CompanionAssets/bytebot"
source_image="$asset_dir/source/lifecycle-reference.png"

if ! command -v ffmpeg >/dev/null 2>&1; then
    echo "ffmpeg is required to regenerate ByteBot sprite sheets." >&2
    exit 1
fi
if [[ ! -f "$source_image" ]]; then
    echo "Missing ByteBot lifecycle source: $source_image" >&2
    exit 1
fi

temporary_dir="$(mktemp -d)"
trap 'rm -rf "$temporary_dir"' EXIT

stage_names=(egg baby adult)
stage_y=(97 388 657)
pose_x=(76 302 527 754 980 1207)

for stage_index in "${!stage_names[@]}"; do
    stage="${stage_names[$stage_index]}"
    y="${stage_y[$stage_index]}"
    for pose in "${!pose_x[@]}"; do
        ffmpeg -v error -y \
            -i "$source_image" \
            -vf "crop=256:256:${pose_x[$pose]}:$y,colorkey=0xFF00FF:0.12:0,scale=60:60:flags=neighbor,pad=64:64:2:2:color=black@0,format=rgba" \
            -frames:v 1 \
            "$temporary_dir/${stage}-${pose}.png"
    done
done

render_sheet() {
    local stage="$1"
    local output="$asset_dir/$stage.png"
    local input_args=()
    local filters=""
    local previous="[0:v]"
    local input_index=1

    add_frame() {
        local pose="$1"
        local column="$2"
        local row="$3"
        local dx="$4"
        local dy="$5"
        local next="[layer$input_index]"
        input_args+=(-i "$temporary_dir/${stage}-${pose}.png")
        filters+="${previous}[${input_index}:v]overlay=x=$((column * 64 + dx)):y=$((row * 64 + dy)):format=auto${next};"
        previous="$next"
        input_index=$((input_index + 1))
    }

    add_frame 0 0 0 0 1
    add_frame 0 1 0 0 0
    add_frame 0 2 0 0 1
    add_frame 0 3 0 0 2

    add_frame 1 0 1 0 1
    add_frame 1 1 1 0 0
    add_frame 1 2 1 0 1
    add_frame 1 3 1 0 0
    add_frame 1 4 1 0 1
    add_frame 1 5 1 0 0

    add_frame 4 0 2 0 1
    add_frame 4 1 2 1 1
    add_frame 4 2 2 0 1
    add_frame 4 3 2 -1 1

    add_frame 2 0 3 -1 1
    add_frame 2 1 3 1 1
    add_frame 2 2 3 -1 1
    add_frame 2 3 3 1 1

    add_frame 3 0 4 0 2
    add_frame 3 1 4 0 0
    add_frame 3 2 4 0 -2
    add_frame 3 3 4 0 0
    add_frame 3 4 4 0 2
    add_frame 3 5 4 0 1

    add_frame 5 0 5 0 1
    add_frame 5 1 5 0 1
    add_frame 5 2 5 0 2
    add_frame 5 3 5 0 2

    filters="${filters%;}"
    ffmpeg -v error -y \
        -f lavfi \
        -i "color=c=black@0:s=512x384:d=1,format=rgba" \
        "${input_args[@]}" \
        -filter_complex "$filters" \
        -map "$previous" \
        -frames:v 1 \
        "$output"
}

for stage in "${stage_names[@]}"; do
    render_sheet "$stage"
done

echo "Generated ByteBot sprite sheets in $asset_dir"
